/**
 * Lowband — browser demo.
 *
 * A Hi8 tape played back on a Video8 deck. Hi8 moved the luma's FM carrier up
 * (5.7–7.7 MHz against Video8's 4.2–5.4) and left the colour-under chroma
 * where it was, so a Video8 deck reads the Hi8 carrier through a channel and
 * a demodulator built for its own: the contrast comes out 5/3 too high, the
 * mismatched emphasis trails a glow after every highlight and lifts the black
 * at the clamp, bright edges throw black streaks where their overshoot leaves
 * the deck's band, and with tape noise the highlights break up first.
 *
 * Like receipt and colourunder, this plugin is **not only a shader**, and the
 * two halves of the page are not equally faithful:
 *
 *   The shaders are the plugin's. The version line, the `kCommon` block and
 *   the three bodies of `source/Shaders.cpp` (vertex, intake, display) are
 *   spliced into the generated block below by `demo/tools/sync_shaders.py`,
 *   tabs and comments included, and `assemble` below is Shaders.cpp's.
 *   `demo/tools/check_shaders.py --dump` compares every assembled stage with
 *   what the plugin compiles (`lbtest --dump-shaders`); `tools/verify.sh`
 *   runs it.
 *
 *   The CPU engine is a PORT. In the plugin the luma is a real FM signal at
 *   40.5 MHz, recorded, played back and demodulated in C++ on worker
 *   threads (Engine.cpp, Dsp.cpp, Model.cpp). `demo/engine.js`, `dsp.js` and
 *   `model.js` are a hand translation of it, float for float, and
 *   `demo/tools/check_port.sh` compares it with the plugin's own C++, run with
 *   its constructor and ProcessOpenGL cut out of Lowband.cpp and GL replaced
 *   by a recorder: bit-identical. This file's GL half (which WebGL object each
 *   name is, the read-back, the draws) only a reader and the comparison
 *   against `lbtest --pipe` in AGENTS.md check.
 *
 * ------------------------------------------------------ the frame
 *
 *   beginFrame  model.js: the settings, the clock, the video frame (every
 *               frame the page draws, as the plugin's clock sees every frame)
 *   intake      the host frame onto the standard's raster, P x N RGBA32F,
 *               and read back
 *   engine      engine.js in Web Workers (engine-worker.js), the frame's
 *               lines split between them; then the clamp and the AGC
 *   upload      the deck's picture, P x N RGBA32F
 *   display     nearest line per row, Catmull-Rom across, R'G'B', Mix
 *
 * The plugin does all five inside one ProcessOpenGL. Here the engine takes
 * longer than a frame, so the intake runs when the workers are free and the
 * display draws the LAST frame they finished, with the input that frame was
 * made from. Paused or stepped, that is exactly the frame shown.
 */

import { mountDemo } from './vendor/demo.js';
import { Program, PassBuffer, bindTexture } from './vendor/gl.js';
import {
  Instance, DECLARATIONS, PT, controls, passes, kPAL, kNTSC, kHi8, kVideo8, standardOf, formatOf, playbackMode, noiseSigma,
} from './model.js';
import { Engine, processRows, finishFrame, frameDropouts } from './engine.js';

//=== BEGIN GENERATED by demo/tools/sync_shaders.py from source/Shaders.cpp -- do not edit by hand.

// source/Shaders.cpp, verbatim. `assemble` (below the block) is Shaders.cpp's.
const K_VERSION = "#version 410 core";

const VERTEX_BODY = `
layout( location = 0 ) in vec4 vPosition;
layout( location = 1 ) in vec2 vUV;

out vec2 uv;

void main()
{
	gl_Position = vPosition;
	uv = vUV;
}
`;

const COMMON = `
const float kUScale = 0.492111;
const float kVScale = 0.877283;

vec3 rgbToYuv( vec3 c )
{
	float y = 0.299 * c.r + 0.587 * c.g + 0.114 * c.b;
	return vec3( y, kUScale * ( c.b - y ), kVScale * ( c.r - y ) );
}

vec3 yuvToRgb( vec3 yuv )
{
	float r = yuv.x + yuv.z / kVScale;
	float b = yuv.x + yuv.y / kUScale;
	float g = ( yuv.x - 0.299 * r - 0.114 * b ) / 0.587;
	return vec3( r, g, b );
}
`;

const INTAKE_BODY = `
uniform sampler2D Source;
uniform int HostW;
uniform int HostH;
uniform int Pixels;
uniform int Lines;

out vec4 fragColor;

void main()
{
	ivec2 p = ivec2( gl_FragCoord.xy );
	int ylo = p.y * HostH;
	int yhi = ( p.y + 1 ) * HostH;
	int r0  = ylo / Lines;
	int r1  = ( yhi - 1 ) / Lines;
	int xlo = p.x * HostW;
	int xhi = ( p.x + 1 ) * HostW;
	int c0  = xlo / Pixels;
	int c1  = ( xhi - 1 ) / Pixels;
	vec4 sum = vec4( 0.0 );
	for( int r = r0; r <= r1; ++r )
	{
		int oy = min( ( r + 1 ) * Lines, yhi ) - max( r * Lines, ylo );
		vec4 row = vec4( 0.0 );
		for( int c = c0; c <= c1; ++c )
		{
			int ox = min( ( c + 1 ) * Pixels, xhi ) - max( c * Pixels, xlo );
			row += float( ox ) * texelFetch( Source, ivec2( c, HostH - 1 - r ), 0 );
		}
		sum += float( oy ) * row;
	}
	vec4 avg  = sum / ( float( HostH ) * float( HostW ) );
	fragColor = vec4( rgbToYuv( avg.rgb ), avg.a );
}
`;

const DISPLAY_BODY = `
uniform sampler2D Lines;
uniform sampler2D Source;
uniform int HostW;
uniform int HostH;
uniform int LineCount;
uniform int Pixels;
uniform float MixAmount;

in vec2 uv;
out vec4 fragColor;

vec3 tap( int i, int l )
{
	return texelFetch( Lines, ivec2( clamp( i, 0, Pixels - 1 ), l ), 0 ).xyz;
}

void main()
{
	int x   = clamp( int( floor( uv.x * float( HostW ) ) ), 0, HostW - 1 );
	int rgl = clamp( int( floor( uv.y * float( HostH ) ) ), 0, HostH - 1 );
	int r   = HostH - 1 - rgl;
	int l   = ( ( 2 * r + 1 ) * LineCount ) / ( 2 * HostH );

	float s  = ( float( x ) + 0.5 ) * float( Pixels ) / float( HostW ) - 0.5;
	float i0 = floor( s );
	float t  = s - i0;
	int i    = int( i0 );
	float t2 = t * t, t3 = t2 * t;
	float w0 = 0.5 * ( -t3 + 2.0 * t2 - t );
	float w1 = 0.5 * ( 3.0 * t3 - 5.0 * t2 + 2.0 );
	float w2 = 0.5 * ( -3.0 * t3 + 4.0 * t2 + t );
	float w3 = 0.5 * ( t3 - t2 );
	vec3 yuv = w0 * tap( i - 1, l ) + w1 * tap( i, l ) + w2 * tap( i + 1, l ) + w3 * tap( i + 2, l );

	vec4 src  = texelFetch( Source, ivec2( x, rgl ), 0 );
	vec3 rgb  = clamp( yuvToRgb( yuv ), 0.0, 1.0 );
	fragColor = vec4( mix( src.rgb, rgb, MixAmount ), mix( src.a, 1.0, MixAmount ) );
}
`;

//=== END GENERATED

/// Which stages Shaders.cpp assembles with kCommon in front
/// (check_shaders.py holds this to Shaders.cpp's stage functions).
const STAGE_COMMON = {
  VERTEX_BODY: false,
  INTAKE_BODY: true,
  DISPLAY_BODY: true,
};

/// Shaders.cpp's assemble( body, common ).
const assemble = (body, common) => `${K_VERSION}\n${common ? COMMON : ''}${body}`;

//===========================================================================
// The engine's workers.
//===========================================================================

/// The plugin's defaultThreads(): the cores less one for the host, at most eight.
const workerCount = () => {
  const cores = typeof navigator !== 'undefined' && navigator.hardwareConcurrency ? navigator.hardwareConcurrency : 2;
  return Math.min(8, Math.max(1, cores - 1));
};

const deck = {
  workers: [],
  failed: false,
  busy: false,
  nextId: 1,
  job: null, // the frame in flight
  parts: [],
  pending: 0,
  done: null, // the last finished frame
  times: [], // finish times, for the rate
  inline: null, // the engine on the page's own thread, if there are no workers
};

/** Set once mountDemo returns: the kit's redraw and its state. */
let redraw = () => {};
let kitState = null;
/**
 * What the last frame handed to the workers was made of (the clock, the
 * parameters, the clip, the size). Paused, a new frame of tape starts only
 * when this changes, so showing a finished frame does not start it again.
 */
let lastKey = null;

function deckStart() {
  if (deck.workers.length || deck.failed) return;
  try {
    for (let i = 0; i < workerCount(); i += 1) {
      const w = new Worker(new URL('./engine-worker.js', import.meta.url), { type: 'module' });
      w.onmessage = (event) => deckPart(event.data);
      w.onerror = (event) => {
        // eslint-disable-next-line no-console
        console.error('engine-worker', event.message);
      };
      deck.workers.push(w);
    }
  } catch {
    // No module workers: run the engine on the page's thread, as the plugin
    // runs it in line, and let the page stall. Said under the picture.
    deck.workers = [];
    deck.failed = true;
    deck.inline = new Engine();
  }
}

function deckPart(msg) {
  const job = deck.job;
  if (!job || msg.id !== job.id) return;
  deck.parts.push(msg);
  job.workerMs = Math.max(job.workerMs, msg.ms);
  deck.pending -= 1;
  if (deck.pending > 0) return;
  deckFinish(finishFrame(deck.parts, job.N, job.P, job.settings));
}

function deckFinish(result) {
  const job = deck.job;
  const now = performance.now();
  deck.done = { ...job, lines: result.lines, depth: result.depth, gain: result.gain, ms: now - job.started, uploaded: false };
  deck.times.push(now);
  while (deck.times.length > 1 && now - deck.times[0] > 3000) deck.times.shift();
  deck.busy = false;
  deck.job = null;
  deck.parts = [];
  redraw();
}

/** Hand a frame's intake to the workers: each its rows, and the two rows before them. */
function deckRun(job) {
  deck.busy = true;
  deck.job = job;
  deck.parts = [];
  job.started = performance.now();
  job.workerMs = 0;
  const { P, N } = job;
  if (deck.failed || deck.workers.length === 0) {
    deck.inline = deck.inline ?? new Engine();
    const part = processRows(deck.inline, job.intake, 0, 0, N, N, P, job.settings, job.drops);
    job.workerMs = performance.now() - job.started;
    deckFinish(finishFrame([part], N, P, job.settings));
    return;
  }
  const n = Math.min(deck.workers.length, N);
  deck.pending = n;
  for (let w = 0; w < n; w += 1) {
    const r0 = Math.floor((N * w) / n);
    const r1 = Math.floor((N * (w + 1)) / n);
    const base = Math.max(0, r0 - 2);
    const data = job.intake.slice(base * P * 4, r1 * P * 4);
    deck.workers[w].postMessage(
      { id: job.id, settings: job.settings, drops: job.drops, P, N, r0, r1, base, data: data.buffer },
      [data.buffer],
    );
  }
}

//===========================================================================
// The renderer: Lowband::InitGL and the GL half of ProcessOpenGL.
//===========================================================================

/// What the line under the canvas reports. Filled by the renderer.
const telemetry = {
  ticked: false, seconds: 0, videoFrame: 0, settings: null, P: 0, N: 0,
  shown: null, missing: [], workers: 0, rate: 0, behind: 0,
};

/// For a driven check (AGENTS.md, "Browser demo"). `fresh()` puts the plugin
/// instance back to a newly created one; `afterRender(gl, info)` runs inside
/// the frame, after the display pass, so it can read the canvas back.
const hooks = { afterRender: null, fresh: null };

function createRenderer(gl, quad) {
  // InitGL: both stages, as Shaders.cpp assembles them.
  const vertex = assemble(VERTEX_BODY, STAGE_COMMON.VERTEX_BODY);
  const programs = {
    intake: new Program(gl, vertex, assemble(INTAKE_BODY, STAGE_COMMON.INTAKE_BODY), 'intake'),
    display: new Program(gl, vertex, assemble(DISPLAY_BODY, STAGE_COMMON.DISPLAY_BODY), 'display'),
  };

  // The plugin's buffers: the intake P x N RGBA32F, nearest; the deck's
  // picture P x N RGBA32F, nearest (every read is texelFetch).
  const intake = new PassBuffer(gl, { filter: 'nearest' });
  let linesTexture = null;
  let linesW = 0;
  let linesH = 0;
  // Not the plugin's: the input the frame in flight was made from, so the
  // display mixes the deck's picture with ITS source, not a later one.
  const held = new PassBuffer(gl, { filter: 'nearest' });
  const readFbo = gl.createFramebuffer();

  let instance = new Instance();
  hooks.fresh = () => {
    instance = new Instance();
    deck.done = null;
    deck.job = null;
    deck.busy = false;
    deck.nextId += 1;
    lastKey = null;
  };

  const parameterFloats = (params) => {
    const p = new Array(DECLARATIONS.length).fill(0);
    p[PT.RECORDING] = params.get('recording');
    p[PT.TAPE_NOISE] = params.get('tapeNoise');
    p[PT.DROPOUTS] = params.get('dropouts');
    p[PT.DECK] = params.get('deck');
    p[PT.STANDARD] = params.get('standard');
    p[PT.HEAD_CLOG] = params.get('headClog');
    p[PT.SYNC_AGC] = params.get('syncAgc');
    p[PT.MIX] = params.get('mix');
    return p.map(Math.fround);
  };

  const draw = (program, pass, textureOf) => {
    const prog = programs[program].use();
    for (const [k, v] of Object.entries(pass.ints)) prog.setInt(k, v);
    for (const [k, v] of Object.entries(pass.floats)) prog.set(k, v);
    pass.textures.forEach((name, unit) => bindTexture(gl, unit, textureOf(name)));
    gl.activeTexture(gl.TEXTURE0);
    quad.draw();
    for (let unit = pass.textures.length - 1; unit >= 0; --unit) bindTexture(gl, unit, null);
    gl.activeTexture(gl.TEXTURE0);
  };

  return {
    render({ input, params, width, height, time }) {
      const W = width;
      const H = height;
      deckStart();

      // Lowband::SetTime, then the head of ProcessOpenGL: every frame the
      // page draws is a frame the plugin's clock sees.
      instance.setTime(time);
      const frame = instance.beginFrame(parameterFloats(params), W, H);
      const { P, N, settings } = frame;
      const plan = passes(W, H, P, N, frame.mixAmount);
      gl.disable(gl.BLEND);

      // A new frame of tape when the workers are free -- and, paused, only
      // when something about the frame has changed.
      const key = JSON.stringify([time, W, H, kitState?.sourceId, params.values]);
      const playing = kitState ? kitState.playing : true;
      if (!deck.busy && (playing || key !== lastKey)) {
        lastKey = key;
        intake.ensure(P, N, gl.RGBA32F);
        intake.bind();
        draw('intake', plan[0], () => input.texture);
        const data = new Float32Array(P * N * 4);
        gl.pixelStorei(gl.PACK_ALIGNMENT, 4);
        gl.readPixels(0, 0, P, N, gl.RGBA, gl.FLOAT, data);

        // Keep the input this frame was made from, for the display's Mix.
        held.ensure(W, H, gl.RGBA8);
        gl.bindFramebuffer(gl.READ_FRAMEBUFFER, readFbo);
        gl.framebufferTexture2D(gl.READ_FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, input.texture, 0);
        gl.bindFramebuffer(gl.DRAW_FRAMEBUFFER, held.fbo);
        gl.blitFramebuffer(0, 0, W, H, 0, 0, W, H, gl.COLOR_BUFFER_BIT, gl.NEAREST);
        gl.bindFramebuffer(gl.READ_FRAMEBUFFER, null);
        gl.bindFramebuffer(gl.DRAW_FRAMEBUFFER, null);

        const id = deck.nextId;
        deck.nextId += 1;
        deckRun({
          id, P, N, W, H, settings, intake: data, drops: frameDropouts(settings, N),
          seconds: frame.seconds, time,
        });
      }

      // The last finished frame of tape, uploaded once.
      const shown = deck.done;
      if (shown && !shown.uploaded) {
        if (linesTexture === null || linesW !== shown.P || linesH !== shown.N) {
          if (linesTexture !== null) gl.deleteTexture(linesTexture);
          linesTexture = gl.createTexture();
          gl.bindTexture(gl.TEXTURE_2D, linesTexture);
          gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA32F, shown.P, shown.N, 0, gl.RGBA, gl.FLOAT, null);
          gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
          gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
          gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
          gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
          linesW = shown.P;
          linesH = shown.N;
        }
        gl.bindTexture(gl.TEXTURE_2D, linesTexture);
        gl.pixelStorei(gl.UNPACK_ALIGNMENT, 4);
        gl.texSubImage2D(gl.TEXTURE_2D, 0, 0, 0, shown.P, shown.N, gl.RGBA, gl.FLOAT, shown.lines);
        gl.bindTexture(gl.TEXTURE_2D, null);
        shown.uploaded = true;
      }

      // Display: the frame of tape, over the input it was made from.
      gl.bindFramebuffer(gl.FRAMEBUFFER, null);
      gl.viewport(0, 0, W, H);
      if (shown) {
        const display = passes(W, H, shown.P, shown.N, frame.mixAmount)[1];
        const source = shown.W === W && shown.H === H ? held.texture : input.texture;
        draw('display', display, (name) => (name === 'lines' ? linesTexture : source));
      }

      telemetry.ticked = true;
      telemetry.seconds = frame.seconds;
      telemetry.videoFrame = settings.videoFrame;
      telemetry.settings = settings;
      telemetry.P = P;
      telemetry.N = N;
      telemetry.shown = shown;
      telemetry.workers = deck.failed ? 0 : deck.workers.length;
      const t = deck.times;
      telemetry.rate = t.length > 1 ? (1000 * (t.length - 1)) / (t[t.length - 1] - t[0]) : 0;
      telemetry.behind = shown ? Math.max(0, frame.seconds - shown.seconds) : 0;
      // A uniform name the shader does not have is a dead control (glUniform
      // on -1 is a no-op); the kit counts them.
      telemetry.missing = Object.entries(programs).flatMap(([name, p]) => [...p.missing].map((u) => `${name}.${u}`));

      if (hooks.afterRender) hooks.afterRender(gl, { shown, held, readFbo, W, H });
    },
  };
}

//===========================================================================
// The controls, read out of Lowband::Lowband() (model.js's DECLARATIONS,
// which check_port.sh holds to the constructor): same names, same groups,
// same order, same defaults, same dropdown elements. Absent: the About block.
//===========================================================================

const IDS = ['recording', 'tapeNoise', 'dropouts', 'deck', 'standard', 'headClog', 'syncAgc', 'mix'];

const HINTS = {
  recording: {
    hint: 'The tape’s format. Video8 records the luma as an FM carrier from 4.2 MHz (sync tip) to 5.4 MHz (peak white), 1.2 MHz of deviation, with a 1.3 µs emphasis; Hi8 from 5.7 to 7.7 MHz, 2.0 MHz, 0.47 µs. The colour-under chroma is the same in both.',
  },
  tapeNoise: {
    display: (v) => (controls.noiseOn(v) ? `${controls.cnrDb(v).toFixed(1)} dB CNR` : 'off'),
    hint: 'The head amplifier’s noise. Off at 0; above it, the carrier-to-noise ratio over the Video8 deck’s band (1.9–7.0 MHz), from 46 dB down to 10 dB. A density, so the same setting is the same tape whichever deck reads it. On a Hi8 tape in a Video8 deck white’s carrier sits furthest outside the band, so the highlights break up first.',
  },
  dropouts: {
    display: (v) => `${controls.dropoutsPerFrame(v).toFixed(1)} / frame`,
    hint: 'Missing oxide: 30 v² expected a video frame (at most 64), each a dip of the carrier by 30 dB for 1–25 µs, with 0.3 µs raised-cosine edges, on a random line. The limiter loses the carrier and the demodulator reads what is left.',
  },
  deck: {
    hint: 'The deck the tape is played on. A Video8 deck has one mode and reads every tape as Video8; a Hi8 deck plays each tape in its own mode. So of the four combinations only a Hi8 tape on a Video8 deck is broken; the other three are the clean references.',
  },
  standard: {
    hint: 'PAL (625/50: 576 lines of 701 pixels, 64 µs) or NTSC (525/59.94: 480 lines of 711). The chain always runs on the standard’s own raster, whatever the composition size. The noise and the dropouts change at its frame rate, 25 or 29.97 a second.',
  },
  headClog: {
    display: (v) => `${(controls.clogMetres(v) * 1e6).toFixed(3)} µm`,
    hint: 'The head-to-tape spacing a dirty head adds, 0.15 v µm: Wallace’s spacing loss, 54.6 d / λ dB, as a 49-tap zero-phase filter on the carrier. It costs the high carriers most, so it pushes Hi8’s white below threshold first.',
  },
  syncAgc: {
    hint: 'Off: the monitor clamps black on the back porch and nothing else. On: it also scales the picture so the sync is its nominal height, from the frame’s mean sync depth — which on a Hi8 tape takes back only part of the 5/3, because the sync is read through the same mismatched emphasis and measures short.',
  },
  mix: {
    display: (v) => `${(100 * controls.amount(v)).toFixed(0)}%`,
    hint: 'The tape against the input. Output alpha is mix( source alpha, 1, Mix ): at 1 the picture is opaque, because a tape has no alpha.',
  },
};

function declarationToKit(d, id) {
  const extra = HINTS[id] ?? {};
  const base = { id, name: d.name, group: d.group, hint: extra.hint };
  if (d.type === 'option') return { ...base, type: 'option', elements: d.elements, default: Math.round(d.default) };
  if (d.type === 'boolean') return { ...base, type: 'boolean', default: d.default };
  return { ...base, type: 'standard', default: d.default, display: extra.display };
}

const PARAMS = DECLARATIONS.map((d, i) => declarationToKit(d, IDS[i]));

const ENGINE_NOTE = (n) => (n > 0 ? `${n} Web Worker${n === 1 ? '' : 's'}` : 'the page’s own thread (no module workers here)');

const demo = mountDemo({
  name: 'Lowband',
  pluginId: 'LB01',
  kind: 'effect',
  tagline:
    'A Hi8 tape played back on a Video8 deck. The luma is a real FM signal: written by Hi8 at 5.7–7.7 MHz and read by a Video8 deck’s channel and demodulator built for 4.2–5.4 MHz. The contrast comes out 5/3 too high, a glow trails every highlight, the black lifts, bright edges throw black streaks, and with tape noise the highlights break up first. The colour-under chroma is common to both formats, so the colour survives.',
  repo: 'https://github.com/stoatworks-labs/lowband',

  // The stock sentence says "same maths", which is only half the truth here:
  // the shaders are the plugin's, the engine between them is a port.
  blurb:
    'It is Lowband’s own GLSL — the intake and display passes — ported from the repository to WebGL2 and running on your GPU, around a JavaScript port of the plugin’s CPU engine: the FM recording, the tape and the Video8 deck’s demodulator, at 40.5 MHz. The port runs in Web Workers at a lower frame rate than the plugin; a script in the repository checks it against the plugin’s own C++, but on this page you are trusting it. It runs on generated clips in this page, with the plugin’s own parameters and no install.',

  // RGBA32F intake and deck picture, as in the plugin.
  needFloat: true,
  // At Mix below 1 the output carries the source's alpha.
  showBackdrop: true,

  params: PARAMS,

  // The scene first: the glow, the lifted black and the streaks all read off
  // its edges. Lights on black is where the highlights break up; the ramp
  // shows the 5/3 and the clip; the bars that the colour survives.
  sources: ['scene', 'spot', 'ramp', 'bars', 'grid', 'detail', 'bars100', 'alpha'],

  // The plugin ships no factory presets. These are the page's own, expressed
  // entirely in the plugin's parameters and reachable with the controls.
  presets: {
    'Hi8 tape, Video8 deck (the defaults)': {},
    'Video8 tape, Video8 deck: clean': { recording: kVideo8 },
    'Hi8 tape, Hi8 deck: clean': { deck: kHi8 },
    'Only the mismatch (no noise, clog or dropouts)': { tapeNoise: 0, dropouts: 0, headClog: 0 },
    'Snow (Tape Noise 0.7, Head Clog 0.55)': { tapeNoise: 0.7, headClog: 0.55 },
    'A badly clogged head': { headClog: 1 },
    'A worn tape (Dropouts 0.6)': { dropouts: 0.6 },
    'Sync AGC on': { syncAgc: 1 },
    'NTSC': { standard: kNTSC },
  },

  differences: [
    'The CPU engine is a PORT, not the plugin’s own code. In Lowband the luma is an FM signal run in C++ at 40.5 MHz: the composite line, the camcorder’s low-pass, pre-emphasis and clips, the modulator, the head clog’s filter, the dropouts and the head amplifier’s noise, the deck’s RF band, the limiter and the zero-crossing demodulator, its low-pass, de-emphasis and map, the monitor’s box filter, clamp and AGC, and the chroma’s low-pass (Engine.cpp, Dsp.cpp, Model.cpp, Controls.cpp, Clock.cpp). All of it is ported to JavaScript line for line, every float operation rounded where the C++ rounds (demo/engine.js, dsp.js, model.js). The repository’s demo/tools/check_port.sh compiles the plugin’s own C++ with the constructor and the whole of ProcessOpenGL cut out of Lowband.cpp, GL replaced by a recorder, and hands both the same intake: over ten scenarios and 25 frames, the 38.9 million floats of the deck’s uploaded picture are bit-identical to the C++ as written and to the plugin’s Intel slice. The plugin’s Apple-silicon slice is compiled with fused multiply-adds, which JavaScript does not have: against it 450 of those floats differ by more than 1/255, all of them under tape noise, at the demodulator’s threshold, where one rounding can add or lose a zero crossing. Nothing on this page runs that check; you are trusting it.',
    'The engine runs at a lower frame rate than the plugin. The plugin runs it inside every frame, eight lines in lock step on up to eight threads (2.6 ms at the defaults; 14 ms on one thread). The port takes about a quarter of a second of one core a frame, so the page splits each frame’s lines across Web Workers (as many as the plugin would use threads: the cores less one, at most eight) and shows the last frame they finished. While a clip plays the picture updates at the rate shown under it and runs a little behind the clip; paused or stepped, it is exactly the frame shown. At Mix below 1 the input under it is the frame the deck was handed, not a later one.',
    'The shaders are not a port. The version line, the kCommon block and the intake and display bodies are the plugin’s own GLSL, assembled as Shaders.cpp assembles them; demo/tools/check_shaders.py compares every assembled stage with what the plugin compiles and fails the repository’s verify script if a character drifts.',
    'The buffers are the plugin’s: the intake is the standard’s raster (701 × 576 or 711 × 480) in RGBA32F, read back in floats, and the deck’s picture goes up as the same. WebGL2 needs EXT_color_buffer_float for that; the page refuses to start without it rather than fall back to 8 bits.',
    'JavaScript’s Math.tan, sin, cos, exp, log and pow are not the platform’s libm, and it has no erfc at all (the page computes its own, for the Gaussian table’s Halley step). So the filter designs’ doubles, the deck’s delay compensation (by up to 2 ulp) and the dropouts’ ends (by 1 ulp) can differ from the plugin’s in their last bits; every float the chain runs with, the 65,536-entry Gaussian table and every dropout’s sample are identical in the check.',
    'The clock is the kit’s, in declared seconds, so the plugin’s vote on its host’s clock unit never runs. Everything downstream is the plugin’s rule, ported: seconds since the first frame in double, the video frame floor(t × 25) or floor(t × 29.97) seeding the noise and the dropouts, and the clock updated on every frame the page draws, whether or not the workers take that frame. A paused page re-renders the same video frame, so the noise holds still; Restart sends the clock back to 0, which the plugin reads as a host clock running backwards and steps on by one nominal frame (1/60 s). The kit caps a frame at 0.1 s, so the plugin’s other jump (a gap over 0.5 s) never happens here.',
    'The plugin’s input is Resolume’s texture at the clip’s own size; here it is a generated clip at the composition size you choose (640 × 360 to 1920 × 1080), or your own image or video at its size. The chain runs on the standard’s own raster at any size, as in the plugin.',
    'There is no sound. The plugin has none either: a Video8 deck’s AFM audio is not modelled, and no control is audio-driven.',
    'The harness-only hooks (Perturb, the quiet switch, the forced dropout, the thread count) are set to what the shipped plugin sets them to: off. The negative controls and the checks lbtest runs through them are not on this page. The About block is absent, as on every page in this suite.',
    'The format’s figures are the plugin’s, with the plugin’s confidence: the FM carriers and deviations are confirmed from three sources; the emphasis time constants and the shelf come from vhs-decode alone; the deck’s RF band is a decoder’s filters standing in for a real head, equaliser and RF stage, and is the number the look depends on most; the noise levels and the clog’s range are chosen; nobody has compared the result with a real Video8 deck playing a Hi8 tape. The repository’s AGENTS.md and ATTRIBUTIONS.md say which is which.',
  ],

  createRenderer,
});

if (demo) {
  redraw = demo.redraw;
  kitState = demo.state;
}

// For a driven check (AGENTS.md, "Browser demo"): the kit's state and redraw,
// the telemetry, the hooks and the deck, so a script can pause, set the clock
// to n / 60, wait for that frame of tape and read it back, as
// `lbtest --pipe --fps 60` renders it.
window.__lowbandDemo = { demo, telemetry, hooks, deck, controls };

//---------------------------------------------------------------------------
// Under the canvas: a line reporting what the ported deck is doing. Skipped in
// embed mode, where there is no reader.
//---------------------------------------------------------------------------
if (demo && !new URLSearchParams(window.location.search).has('embed')) {
  const stage = document.querySelector('.stage');
  if (stage) {
    const line = document.createElement('p');
    line.className = 'stage__status';
    line.id = 'telemetry';
    stage.append(line);
    setInterval(() => {
      if (!telemetry.ticked) return;
      const t = telemetry;
      const s = t.settings;
      const shown = t.shown;
      const mode = playbackMode(s.deck, s.recording);
      const tape = `${formatOf(s.recording).name} tape on a ${formatOf(s.deck).name} deck${mode !== s.recording ? ' (read as Video8)' : ''}`;
      const noise = s.noise ? `${s.cnrDb.toFixed(1)} dB CNR (σ ${noiseSigma(s.cnrDb).toFixed(4)})` : 'no noise';
      const head = `${standardOf(s.standard) === standardOf(kPAL) ? 'PAL' : 'NTSC'}, ${tape}; ${noise}; head clog ${(s.clogMetres * 1e6).toFixed(3)} µm; ${s.dropoutsPerFrame.toFixed(1)} dropouts a frame expected`;
      const engine = shown
        ? `Showing video frame ${shown.settings.videoFrame} (${shown.P} × ${shown.N}), made in ${shown.ms.toFixed(0)} ms on ${ENGINE_NOTE(t.workers)}; ${t.rate > 0 ? `${t.rate.toFixed(1)} frames of tape a second, ` : ''}${t.behind.toFixed(2)} s behind the clock (video frame ${t.videoFrame}); sync depth ${shown.depth.toFixed(3)} V${shown.settings.syncAgc ? `, AGC gain ${shown.gain.toFixed(3)}` : ''}`
        : `The first frame of tape is still being played, on ${ENGINE_NOTE(t.workers)}`;
      line.textContent = `${head}. ${engine}${t.missing.length ? `; UNMATCHED UNIFORMS: ${t.missing.join(', ')}` : ''}.`;
    }, 250);
  }
}
