"""Copy the plugin's shaders into the demo, by script, never by hand.

    python3 demo/tools/sync_shaders.py          rewrite the generated block of demo/plugin.js
    python3 demo/tools/sync_shaders.py --print  print the block instead

`demo/plugin.js` carries one region between the lines

    //=== BEGIN GENERATED by demo/tools/sync_shaders.py
    //=== END GENERATED

and this script owns it. Everything in it is text lifted out of
`source/Shaders.cpp`: the version line `assemble` prepends (`kVersion`), the
`kCommon` block (BT.601 Y'UV both ways) and the three bodies -- vertex,
intake, display -- each spliced into a JavaScript template literal with its
tabs, its comments and its blank lines exactly as they are. A template literal
cannot hold a raw backtick, a backslash or a `${`, so those three are escaped
(none occurs today) and `check_shaders.py` undoes exactly those three and
refuses any other escape.

What this script does NOT write is the port: `demo/model.js`, `demo/dsp.js`
and `demo/engine.js` (Model.cpp, Controls.cpp, Clock.cpp, Dsp.cpp, Engine.cpp
and the CPU half of Lowband::ProcessOpenGL) are a hand translation, checked
against the C++ by `demo/tools/check_port.sh`.

Run it whenever a shader changes in the plugin, then
`python3 demo/tools/check_shaders.py` (tools/verify.sh runs it) to confirm.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
PLUGIN_JS = os.path.join(REPO, "demo", "plugin.js")

BEGIN = "//=== BEGIN GENERATED by demo/tools/sync_shaders.py"
END = "//=== END GENERATED"

# JS constant, C++ symbol in source/Shaders.cpp. Order is the file's order.
SHADERS = [
    ("VERTEX_BODY", "kVertexBody"),
    ("COMMON", "kCommon"),
    ("INTAKE_BODY", "kIntakeBody"),
    ("DISPLAY_BODY", "kDisplayBody"),
]

# The stages the plugin compiles, as `lbtest --dump-shaders` names them: the
# body, and whether `assemble` puts kCommon in front. Shaders.cpp's Vertex() /
# Intake() / Display() functions, read as data.
STAGES = [
    ("vertex.vert", "VERTEX_BODY", False),
    ("intake.frag", "INTAKE_BODY", True),
    ("display.frag", "DISPLAY_BODY", True),
]


def read(path):
    with open(os.path.join(REPO, path)) as handle:
        return handle.read()


def cpp_shader(source, symbol):
    match = re.search(r'const char\* const ' + symbol + r' = R"\((.*?)\)";', source, re.S)
    if match is None:
        raise SystemExit(f"{symbol} not found in source/Shaders.cpp")
    return match.group(1)


def cpp_version(source):
    match = re.search(r'const char\* const kVersion = "(.*?)\\n";', source)
    if match is None:
        raise SystemExit("kVersion not found in source/Shaders.cpp")
    return match.group(1)


def cpp_stages(source):
    """Which bodies Shaders.cpp's stage functions assemble with kCommon."""
    found = {}
    for fn, body, common in re.findall(r"std::string (\w+)\(\)\s*\{\s*return assemble\( (k\w+)(, true)? \);", source):
        found[body] = bool(common)
    return found


def escape_template(text):
    return text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def block():
    shaders_cpp = read("source/Shaders.cpp")
    out = [BEGIN + " from source/Shaders.cpp -- do not edit by hand.", ""]
    out.append("// source/Shaders.cpp, verbatim. `assemble` (below the block) is Shaders.cpp's.")
    out.append(f'const K_VERSION = "{cpp_version(shaders_cpp)}";')
    out.append("")
    for name, symbol in SHADERS:
        out.append(f"const {name} = `{escape_template(cpp_shader(shaders_cpp, symbol))}`;")
        out.append("")
    out.append(END)
    return "\n".join(out)


def region(js):
    start = js.find(BEGIN)
    stop = js.find(END)
    if start < 0 or stop < 0 or stop < start:
        return None
    return start, stop + len(END)


def main():
    text = block()
    if "--print" in sys.argv:
        print(text)
        return 0
    with open(PLUGIN_JS) as handle:
        js = handle.read()
    where = region(js)
    if where is None:
        raise SystemExit("demo/plugin.js has no generated block (the BEGIN/END GENERATED lines)")
    updated = js[: where[0]] + text + js[where[1]:]
    if updated == js:
        print("demo/plugin.js already matches source/Shaders.cpp")
        return 0
    with open(PLUGIN_JS, "w") as handle:
        handle.write(updated)
    print("demo/plugin.js: generated block rewritten from source/Shaders.cpp")
    return 0


if __name__ == "__main__":
    sys.exit(main())
